Implements filter on ErrorMessage
labbsr0x/servlet-monitor pull request #33
Opened 2021-05-20 11:50 UTC by Ziul

fixes #29 and fixes #30

- support custom regex to filter
- support custom max value
- support to select the correct group of the regex

Signed-off-by: Luiz Oliveira <ziuloliveira@gmail.com>

2021-05-23 05:51 UTC, flaviostutz commented
Thanks for the work!

Please change the attribute names according to the discussion at https://github.com/labbsr0x/servlet-monitor/issues/30.
The names would be "error-info-regex" and "error-info-maxsize"

I don't think we would need the "index" parameter for grouping regex as we won't be using groups in regex. The idea is for this regex to define the characters that would be accepted in output message (see JS code at the begining of https://github.com/labbsr0x/servlet-monitor/issues/30).

2021-05-28 15:04 UTC, Ziul commented
Updated the attribute names according to #30.

The index parameter was for select any group of the regex. Now that I updated the PR to apply the regex as a whitelist it's pointless, so I removed the index. Also reduced the default max size according to #29.

2021-05-31 20:48 UTC, flaviostutz requested changes
Thanks for the changes... we are almost there... see review comments.

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +    private static final String DEFAULT_FILTER_REGEX = "^([a-zA-z0-9 ]{0,120})";
Please change the attribute names according to the discussion at #30.
The names would be "error-info-regex" and "error-info-maxsize"

I don't think we would need the "index" parameter for grouping regex as we won't be using groups in regex. The idea is for this regex to define the characters that would be accepted in output message (see JS code at the begining of #30). Please use default regex from the description in #30.

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +    private int filter_max_size = 120;
Too high default max size. Please check description at #30

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +    private static final String FILTER_REGEX_PARAM = "error-message-regex";
Change name

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +    private static final String FILTER_GROUP_INDEX_PARAM = "error-message-regex-index";
I think this is unnecessary because we didn't discuss about using regex groupings.

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +    private static final String FILTER_MAX_SIZE_PARAM = "error-message-max-size";
Please use "error-info-maxsize" at in #30

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +    private int filter_group_index = 0;
we won't use according to previous discussion in #30

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +    private String filter_regex = "";
We would have a default regex according to #30

2021-05-31 20:48 UTC, flaviostutz commented on README.md
> +It is possible to filter the error message to avoid long messages or personal info exposed in the metrics. To do it, three params may be used: `error-info-regex`, `error-info-regex-index`, and `error
I think we have to remove the "error-info-regex-index" mention here as it is not used anymore.

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +     * Default regex: ^([a-zA-z0-9 ]{0,120})
Documentation is wrong here.

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +            // avoid invalid regex or invalid matcher group index
Log here the exception with "warning" for the app developer to know that something is wrong.

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +    private static final String DEFAULT_FILTER_REGEX = "[^A-zÀ-ú .,]+";
Check if " " is accepted. It would be better to use "\s" for representing spaces in regex.

2021-05-31 20:48 UTC, flaviostutz commented on src/main/java/br/com/labbs/monitor/filter/MetricsCollectorFilter.java
> +     * Default regex: ^([a-zA-z0-9 ]{0,120})
Default regex is wrong here in documentation.

2021-06-08 12:17 UTC, flaviostutz approved these changes
Thanks, man!

2021-06-08 12:18 UTC, flaviostutz approved these changes

2021-06-08 12:19 UTC, merged